name: Build Flutter APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-apk:
    name: Build Flutter APK
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'microsoft'

      # Step 2: Set up Flutter environment
      - name: Set up Flutter
        uses: penkzhou/flutter-action@v2.16.1

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Step 4: Build APK
      - name: Build APK
        run: flutter build apk --release

      # Step 5: Upload APK to GitHub Artifacts
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: flutter-app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
